### ISSUE TITLE
Only redis

### ISSUE THREAD

**Issue by Karman40** [hibiken/asynqmon#119]
Hey,

I checked out the repository and one is a great app. I couldn't find a description of whether the application only works with redis db? I'm using NodeJs and Ubuntu 20.04 and I'm looking for something to manage the redis on the server for which this app would be great.

If all is true this only works with https://github.com/hibiken/asynqmon, doesn't it?

Thnaks a lot!

**Comment by hibiken** [comment]
@Karman40 thank you for opening this issue!

Asynq currently only supports Redis as message broker but we are planning to support other message brokers in the future.

Let me know if that answers your question.

**Comment by Karman40** [comment]
Hello!

Sorry if I was misunderstood, my English is not real.
I have an Ubuntu 20.04 LTS server running only one redis 5.x.x server.

I accidentally found this surface that I liked, but it didn't work. I saw the redis server information, but I didn't see the processors or waiting tasks.

The question was, can the interface be used only with redis, without "Asynq"?

Thanks!

**Comment by hibiken** [comment]
Thank you for clarifying!

I don't think the Web UI is useful for general redis monitoring. It's meant to be used for Asynq specific monitoring / admin purpose.
