### ISSUE TITLE
Could not retreive queues live data

### ISSUE THREAD

**Issue by LINJINTIANDE** [hibiken/asynqmon#121]
Could not retreive queues live data — See the logs for details，But I see the log is request 200
![image](https://user-images.githubusercontent.com/42436479/123019756-adc08d80-d403-11eb-9276-7e265ba24424.png)
![image](https://user-images.githubusercontent.com/42436479/123019778-bb761300-d403-11eb-86f8-11b3ded2655e.png)

**Comment by hibiken** [comment]
Would you mind inspecting the response body using the chrome network tab? (Sorry for a late response!)

**Comment by hibiken** [comment]
Closing this since no updates. Let me know if you are still seeing the issue!
