### ISSUE TITLE
queue not exist

### ISSUE THREAD

**Issue by acgfbr** [hibiken/asynqmon#122]
my worker has up but queues not showing, whats the problem?

![image](https://user-images.githubusercontent.com/8755427/123470252-87991a00-d5ca-11eb-96fb-1299070d992a.png)
![image](https://user-images.githubusercontent.com/8755427/123470307-9a135380-d5ca-11eb-9c51-60865d45574f.png)
![image](https://user-images.githubusercontent.com/8755427/123470350-a9929c80-d5ca-11eb-8e8c-70e5c103cfa8.png)

Thanks

**Comment by acgfbr** [comment]
error says: queue "critical" does not exist

**Comment by crossworth** [comment]
Hello.
Do you have any job on the queue?

I just checked and the queue will only show up if you have jobs on it.

**Comment by acgfbr** [comment]
yeah, i put items but not showing queues, it proccess normally

**Comment by acgfbr** [comment]
![image](https://user-images.githubusercontent.com/8755427/123474198-fdec4b00-d5cf-11eb-9803-ad36ad3c5c5c.png)

**Comment by crossworth** [comment]
With `async cli` do you have the same problem?

https://github.com/hibiken/asynq/tree/master/tools/asynq

**Comment by acgfbr** [comment]
![image](https://user-images.githubusercontent.com/8755427/123496978-656ebe80-d601-11eb-9270-a3a7353da403.png)
solved, my bad guys.

**Comment by mahdiG** [comment]
> ![image](https://user-images.githubusercontent.com/8755427/123496978-656ebe80-d601-11eb-9270-a3a7353da403.png) solved, my bad guys.

How did you solve it?

**Comment by Psuta90** [comment]
> ![image](https://user-images.githubusercontent.com/8755427/123496978-656ebe80-d601-11eb-9270-a3a7353da403.png) solved, my bad guys.

how to soleve this

**Comment by Psuta90** [comment]
> ![image](https://user-images.githubusercontent.com/8755427/123496978-656ebe80-d601-11eb-9270-a3a7353da403.png) solved, my bad guys.

can give me solution how to solve issue like this

**Comment by mahdiG** [comment]
@Psuta90 I had this issue long ago and I think the problem was that the queue WAS created and existed but it showed the queue does not exist error by mistake. I queued a task into the queue and it showed my task in there and the error disappeared.

**Comment by Psuta90** [comment]
> @Psuta90 I had this issue long ago and I think the problem was that the queue WAS created and existed but it showed the queue does not exist error by mistake. I queued a task into the queue and it showed my task in there and the error disappeared.

thanks for your information
