### ISSUE TITLE
got a 502 when state has tasks

### ISSUE THREAD

**Issue by mailbaoer** [hibiken/asynqmon#127]
my asynqmon version is 0.20, and asynq version is 0.18, when a state have tasks, it will show 502 error page, but have no tasks is ok
![screenshot-20210702-120603](https://user-images.githubusercontent.com/5282978/124219017-02fc4d80-db2e-11eb-8e21-b69815806e76.png)
the panic log is below
![screenshot-20210702-155824](https://user-images.githubusercontent.com/5282978/124241455-59798400-db4e-11eb-98b7-18c957a93e85.png)

**Comment by crossworth** [comment]
Hi, looks like you have an invalid uuid on Redis (or invalid protobuf message).

Did you follow the migration guide? 

https://github.com/hibiken/asynq/wiki/Version-Upgrade-Guide-%28from-0.17-to-0.18%29

**Comment by mailbaoer** [comment]
sorry, that's my fault, one server has not update successfully, so it send the old data, thank you for your answer
