### ISSUE TITLE
servers not showing 

### ISSUE THREAD

**Issue by acgfbr** [hibiken/asynqmon#142]
my servers not showing but tasks aparently processing normal

![image](https://user-images.githubusercontent.com/8755427/125504884-9eb8dce9-d8b0-41c9-bb82-a8d9d3770577.png)

![image](https://user-images.githubusercontent.com/8755427/125504921-33c59a98-bf23-4fc2-a16c-cbd8786ec42f.png)

![image](https://user-images.githubusercontent.com/8755427/125504950-bae8e3c2-f096-4be1-8aa9-90c505c879c7.png)

**Comment by crossworth** [comment]
Hi, does`asynqmon` process log have more info? Maybe a panic?

**Comment by acgfbr** [comment]
yes: 
![image](https://user-images.githubusercontent.com/8755427/125535610-19c83fa8-91c1-4761-adc1-96266da28de5.png)

im running on k8s, my helm chart:

![image](https://user-images.githubusercontent.com/8755427/125535716-db936ecc-8a7a-411f-bd8d-0b0d2f007c7c.png)

im run locally and everything works, wtf :(

**Comment by crossworth** [comment]
see https://github.com/hibiken/asynqmon/issues/127, I think is related.

**Comment by acgfbr** [comment]
i found my error, im running asynq with 0.17 version, i wil upgrade, thanks
