### ISSUE TITLE
Missing cluster configuration

### ISSUE THREAD

**Issue by pbarnum** [hibiken/asynqmon#144]
The code indicates that the only way to connect `asynqmon` to `redis` is through a single client connection. This doesn't seem to work when dealing with a cluster setup.

Perhaps if you `strings.Split` the address string and detect multiple IPs, you can then set up the connection using the cluster connection configs.

**Comment by hibiken** [comment]
@pbarnum thank you for opening this issue!

Similar issue #10 
Currently the Web UI doesn't support connecting to Redis Cluster. I'll work on this soon 👍
