### ISSUE TITLE
Record the error info for failed task

### ISSUE THREAD

**Issue by lufishggg** [hibiken/asynqmon#153]
Maybe we can record the error info for failed task which is good for debugging and online monitoring

**Comment by hibiken** [comment]
@lufishggg thank you for opening an issue!

Currently, `asynq` stores the error message from the last failure (if any) and this is shown in the WebUI.
If you need more error info (e.g. entire error history not just the last one, stack trace, etc) and for monitoring/alerting you can probably use an error reporting service (e.g. Bugsnag, Rollbar, Sentry, Airbrake, etc).
Asynq provides [`ErrorHandler`](https://pkg.go.dev/github.com/hibiken/asynq#Config.ErrorHandler) via config so you can report all errors to a error reporting service using this hook:

```go
func reportError(ctx context, task *asynq.Task, err error) {
     // notify error to the error reporting service
}

srv := asynq.NewServer(redisConnOpt, asynq.Config{
     ErrorHandler: asynq.ErrorHandlerFunc(reportError),
})
```

**Comment by lufishggg** [comment]
thanks

**Comment by hibiken** [comment]
Closing this, but feel free to reopen if you have further questions or feedback!
