### ISSUE TITLE
Environment variables as an alternative to cmd flags

### ISSUE THREAD

**Issue by rugwirobaker** [hibiken/asynqmon#161]
Environment variables would make this easy to deploy in an environment such as Heroku or Cloud Run without any modifications. So I propose for asynqmon to read environment variables in case the corresponding flag is not set.

Related to #150

**Comment by hibiken** [comment]
@rugwirobaker thank you for opening this issue!
Makes sense. Would you mind opening a PR for this?

**Comment by hibiken** [comment]
Closed via #198
