### ISSUE TITLE
Could not retreive servers live data.

### ISSUE THREAD

**Issue by StormYudi** [hibiken/asynqmon#166]
Hi, I have a problem with asynqmon: 

Error
Could not retreive servers live data — See the logs for details

But I can see the redis server info from dashboard.

![image](https://user-images.githubusercontent.com/19419186/136176468-c9d4994e-a8bf-41d7-ba2c-391a50efbf2d.png)
![image](https://user-images.githubusercontent.com/19419186/136176934-9abf5dc7-3a9d-48d9-87c9-467c6677fb3d.png)
![image](https://user-images.githubusercontent.com/19419186/136176542-6eb426c3-4138-4f5c-a6ad-4051cfe3418c.png)

Command:
asynqmon --redis-addr=center.xxxxxxxxx:6380 --redis-db=1 --redis-password=xxxxxxxxxxxxxx

Asynq version: 
v0.18.6

Asynqmon version:
0.2.3

Any idea? Thank you.

**Comment by hibiken** [comment]
@StormYudi thanks for opening an issue!
Do you have asynq CLI installed? If so, would you mind running a few commands, such as:
- `asynq queue ls`
- `asynq server ls`
- `asynq stats`
- etc

**Comment by StormYudi** [comment]
Thank you for your support, But I seem to find that it's a version mismatch. I will close this comment now..
