### ISSUE TITLE
Unable to host dashboard through echo http framework

### ISSUE THREAD

**Issue by swagftw** [hibiken/asynqmon#187]
I will try to keep it simple and short

- Using echo http framework
- Redis is up and running
- When trying to hit `localhost:8080/events/dashboard/` blank page is returned with multiple 404 responses as shown below
  - "/events/dashboard/static/js/2.980b0c32.chunk.js" 
  - "/events/dashboard/static/js/main.090c4a40.chunk.js"
  - "/events/dashboard/apple-touch-icon.png" 

 **Check the code below**
```
// events queue 
mon := asynqmon.New(asynqmon.Options{
		RootPath:     "/events/dashboard",
		RedisConnOpt: asynq.RedisClientOpt{Addr: ":6379"},

// registering endpoint
e.GET(mon.RootPath(), func(c echo.Context) error {
		c.Response().Header().Set("Content-Type", "text/html; charset=utf-8")
		c.Response().Header().Set("Transfer-Encoding", "chunked")
		mon.ServeHTTP(c.Response(), c.Request())
		return nil
})
```
OR
```
// events queue 
mon := asynqmon.New(asynqmon.Options{
		RootPath:     "/events/dashboard",
		RedisConnOpt: asynq.RedisClientOpt{Addr: ":6379"},

// registering endpoint
e.GET(mon.RootPath(), echo.WrapHandler(mon))
```

**Comment by zijiwork** [comment]
Hello,  How to integrate dashboards in gin framework

**Comment by tempor1s** [comment]
If anyone runs into this same issue, you are able to integrate Echo and Asynqmon with the following code snippet:

```
e := echo.New()

mon := asynqmon.New(asynqmon.Options{
		RootPath: "/monitoring/tasks",
		RedisConnOpt: asynq.RedisClientOpt{
			Addr: "localhost:6379",
			Password: "",
			DB: 0,
		},
	})

e.Any("/monitoring/tasks/*", echo.WrapHandler(mon))

e.Start(":8080")
```

You should then be able to navigate to `http://localhost:8080/monitoring/tasks/` and view the dashboard.

**Comment by hibiken** [comment]
Thank you @tempor1s!
