### ISSUE TITLE
[Feature Request] Monitor/Read-Only Mode

### ISSUE THREAD

**Issue by aakashbajaj** [hibiken/asynqmon#213]
We can add an additional flag to enable read-only mode that disallows any queue or task edits, just for monitoring the asynq cluster

**Comment by hibiken** [comment]
@aakashbajaj Thank you for creating a feature request!

This has come up in our Gitter channel before, definitely makes sense to add this read-only mode 👍

**Comment by hibiken** [comment]
This is included in the v0.6.0 🎉
