### ISSUE TITLE
Pagination not working on Active Tasks Tab

### ISSUE THREAD

**Issue by hieunguyen1809** [hibiken/asynqmon#219]
Hi guys, I found that the pagination of active tab is not working. I have more than 10 tasks but the next page button is still disabled.
img1
<img width="187" alt="Screen Shot 2022-03-02 at 10 06 23" src="https://user-images.githubusercontent.com/57081022/156287303-6262f3b3-ce6c-4533-8cbb-53ef21cb44fd.png">
img2
<img width="1175" alt="Screen Shot 2022-03-02 at 10 06 15" src="https://user-images.githubusercontent.com/57081022/156287329-df4e9376-9e30-4293-87d7-1c000773522a.png">

**Comment by hibiken** [comment]
@hieunguyen1809 Thank you for reporting this issue!

I was able to squeeze in the fix for this in the version I released today (v0.6.0) 👍
