### ISSUE TITLE
The Metrics menu isn't displaying after Prometheus integrated

### ISSUE THREAD

**Issue by raecoo** [hibiken/asynqmon#222]
I’m tried to integrate the Prometheus with asynqmon to monitor our tasks by the following command, the Metrics menu doesn't appear in the sidebar, but I can access using the `http://localhost:8080/q/metrics?duration=86400` to access the metrics chart.

`./asynqmon -redis-addr="127.0.0.1:6379" -enable-metrics-exporter=true -prometheus-addr=http://127.0.0.1:9090 -redis-db=1`

<img width="1165" alt="asynqmon-metrics-issue" src="https://user-images.githubusercontent.com/4910/158776579-9658328e-cad3-44dc-9963-8742483ac766.png">

I read the relevant code of the UI part and found it seems like a bug.
https://github.com/hibiken/asynqmon/blob/master/ui/src/parseFlags.ts#L14
```  // PROMETHEUS_SERVER_ADDRESS
  if (window.FLAG_PROMETHEUS_SERVER_ADDRESS === undefined) {
    console.log(
      "PROMETHEUS_SERVER_ADDRESS is not defined. Falling back to emtpy string"
    );
    window.PROMETHEUS_SERVER_ADDRESS = "";
  } else if (
    window.FLAG_PROMETHEUS_SERVER_ADDRESS.startsWith(goTmplActionPrefix)
  ) {
    console.log(
      "PROMETHEUS_SERVER_ADDRESS was not evaluated by the server. Falling back to empty string"
    );
    window.PROMETHEUS_SERVER_ADDRESS = "";
  } else {
  }
```
I think it should be assigned in the last else block, otherwise, it won't show.
https://github.com/hibiken/asynqmon/blob/master/ui/src/App.tsx#L244
```
{window.PROMETHEUS_SERVER_ADDRESS && (
    <ListItemLink
    to={paths.QUEUE_METRICS}
    primary="Metrics"
    icon={<TimelineIcon />}
    />
)}
```

Please correct me if anything wrong.

**Comment by hibiken** [comment]
@raecoo Thank you for reporting this!

You are right, I somehow managed to have an empty else block in the committed code 😆 
I'll fix this now, and release a new version of the Web UI with the fix!

**Comment by hibiken** [comment]
Just released a new version v.0.6.1. Please let me know if you are still seeing the issue!

**Comment by raecoo** [comment]
Pretty cool, I've tested and the problem resolved.
Thank you for the fast response.

**Comment by piperck** [comment]
Very helpful thank you. @hibiken
