### ISSUE TITLE
Support sentinel redis

### ISSUE THREAD

**Issue by linhbkhn95** [hibiken/asynqmon#235]
Thanks everyone about lib `asynq`. So, Currently, I use Redis sentinel for storage tasks, I wanna view stats on `asynqmon`. However, I have never seen this lib `asynqmon` tell about integrating with Redis sentinel. Please support me. or I can contribute for this issue if it has not.
Thanks all,

**Comment by hibiken** [comment]
@linhbkhn95 Thank you for opening this issue! 

You should be able to provide the `--redis-url` flag with the format:
```
redis-sentinel://[:password@]host1[:port][,host2:[:port]][,hostN:[:port]][?master=masterName]
```

Let me know if that doesn't work for you!


I'll update the documentation so that others don't come across this same issue.

**Comment by linhbkhn95** [comment]
many thanks @hibiken

**Comment by linhbkhn95** [comment]
I try to test, So I can not run app, please help me :(

**Comment by piupuer** [comment]
> 

I add it in docker container, get error log:
`redis: invalid URL scheme: redis-sentinel`

**Comment by piupuer** [comment]
> @linhbkhn95 Thank you for opening this issue!
> 
> You should be able to provide the `--redis-url` flag with the format:
> 
> ```
> redis-sentinel://[:password@]host1[:port][,host2:[:port]][,hostN:[:port]][?master=masterName]
> ```
> 
> Let me know if that doesn't work for you!
> 
> I'll update the documentation so that others don't come across this same issue.

I add it in docker container, get error log:
`redis: invalid URL scheme: redis-sentinel`
and I saw the source code, use redis.ParseURL, maybe u can use asynq.ParseRedisURI
please fix it, thanks

**Comment by linhbkhn95** [comment]
@hibiken I have a PR to fix this problem at https://github.com/hibiken/asynqmon/pull/240
@piupuer you can use my docker customize at https://hub.docker.com/repository/docker/linhbkhn95/asynqmon/tags, It will support Redis sentinels, currently my project need it for view tasks
many thanks

**Comment by piupuer** [comment]
感谢来信，但您所发的用户不在服务区，请稍后再发！
