### ISSUE TITLE
centos Server: superfluous response.WriteHeader

### ISSUE THREAD

**Issue by xiongdi9456** [hibiken/asynqmon#293]
I run both docker and [asynqmon_v0.7.1_linux_amd64.tar.gz] file in CentOS Server,  they all have some message like

```
Asynq Monitoring WebUI server is listening on port 8080
2023/02/20 12:25:48 http: superfluous response.WriteHeader call from github.com/hibiken/asynqmon.(*uiAssetsHandler).ServeHTTP (static.go:46)
2023/02/20 12:26:05 http: superfluous response.WriteHeader call from github.com/hibiken/asynqmon.(*uiAssetsHandler).ServeHTTP (static.go:46)
2023/02/20 12:26:06 http: superfluous response.WriteHeader call from github.com/hibiken/asynqmon.(*uiAssetsHandler).ServeHTTP (static.go:46)
```

and the web in browser have nothing show up.
The console had an error like:
```
Failed to load resource: net::ERR_INCOMPLETE_CHUNKED_ENCODING
```
Redis is working well, I tested the port is good.

Do you have any idea?

**Comment by mikelaowang** [comment]
It is because your network speed is too low  to load the webui js, well  the Server blocked your request。
Look at the code  ‘cmd/asynqmon/main.go’ at line 179 , change the timeout num  
Then  Build a docker image yourself

**Comment by mikelaowang** [comment]
> I run both docker and [asynqmon_v0.7.1_linux_amd64.tar.gz] file in CentOS Server, they all have some message like
> 
> ```
> Asynq Monitoring WebUI server is listening on port 8080
> 2023/02/20 12:25:48 http: superfluous response.WriteHeader call from github.com/hibiken/asynqmon.(*uiAssetsHandler).ServeHTTP (static.go:46)
> 2023/02/20 12:26:05 http: superfluous response.WriteHeader call from github.com/hibiken/asynqmon.(*uiAssetsHandler).ServeHTTP (static.go:46)
> 2023/02/20 12:26:06 http: superfluous response.WriteHeader call from github.com/hibiken/asynqmon.(*uiAssetsHandler).ServeHTTP (static.go:46)
> ```
> 
> and the web in browser have nothing show up. The console had an error like:
> 
> ```
> Failed to load resource: net::ERR_INCOMPLETE_CHUNKED_ENCODING
> ```
> 
> Redis is working well, I tested the port is good.
> 
> Do you have any idea?

!!!
