### ISSUE TITLE
Ignore error on calculating RDB.MemoryUsage

### ISSUE THREAD

**Issue by NyaMisty** [hibiken/asynqmon#311]
On Redis SaaS platform like Redis Cloud or Upstash, they disable MEMORY USAGE command in Lua script (reporting error "This Redis command is not allowed from scripts"), causing the whole Inspector.GetQueueInfo() function fails. 
As MemoryUsage is not a critical stat data, can we ignore error in memory usage query?

**Comment by NyaMisty** [comment]
Sorry posted on wrong place. I'll repost it in asynq main repo

**Comment by ganlvtech** [comment]
```
sed -i 's/redis\.call("MEMORY".*/0/g' "$(go env GOMODCACHE)/github.com/hibiken/asynq@v0.24.1/internal/rdb/inspect.go"
```

For docker. Modify `Dockerfile`, add

```
RUN sed -i 's/redis\.call("MEMORY".*/0/g' "/go/pkg/mod/github.com/hibiken/asynq@v0.24.1/internal/rdb/inspect.go"
```

after `RUN go mod download`
