### ISSUE TITLE
Hold last choosen time period in Task Processed block

### ISSUE THREAD

**Issue by koddr** [hibiken/asynqmon#69]
Now, if you go to any other section and return to the main screen, the time period will be reset to `LAST 7D`. 

![Screenshot 2021-04-06 at 15 37 08](https://user-images.githubusercontent.com/11155743/113761047-abf9fe80-971f-11eb-9de6-ed06fd41a629.png)

It would be nice if the choices were stored in browser's`localStorage` or cookies, as an option.

**Comment by hibiken** [comment]
Good catch! 
This should be something stored as user settings and should persist across page navigation/refresh.

Also, I noticed that the "page size" option in the task view also doesn't persist, so we need to fix that as well.

Should be a simple change.
I can probably get to it in a few days but if anyone wants to have a go at it, feel free :)
