### ISSUE TITLE
ERR unknown command 'memory'

### ISSUE THREAD

**Issue by victor-wzq** [hibiken/asynqmon#85]
api/queues have error ERR unknown command 'memory'

**Comment by hibiken** [comment]
@victor-wzq thank you for opening an issue.

My guess is that you are running Redis server version below 4.0.
Asynq currently requires redis v4.0+

**Comment by victor-wzq** [comment]
> @victor-wzq thank you for opening an issue.
> 
> My guess is that you are running Redis server version below 4.0.
> Asynq currently requires redis v4.0+

thank you for your answer.
