### ISSUE TITLE
Error UI in Safari and Chrome

### ISSUE THREAD

**Issue by spacecodewor** [hibiken/asynqmon#98]
Hi, the logo in Safari and Chrom is now broken.

And the menu set is different in Safari and Chrome.

While I'm trying to run ui from a local machine and everything comes down to the impossibility of connecting to redis, I'm trying to figure it out.

mostly errors:
"GET / api / redis_info HTTP / 1.1" 500 53

tls: DialWithDialer timed out

But I checked the connection from the local machine and everything works, oddities)
![Снимок экрана 2021-05-08 в 23 38 39](https://user-images.githubusercontent.com/7561665/117552997-8e3df300-b057-11eb-8edb-b0bb1f2b2efa.png)
<img width="2115" alt="Снимок экрана 2021-05-08 в 23 38 50" src="https://user-images.githubusercontent.com/7561665/117552998-9007b680-b057-11eb-958a-0ea1adace805.png">

**Comment by hibiken** [comment]
@spacecodewor Thank you for reporting this issue!
Apologies, I pushed a new image without QA-ing the recent changes. 

I'll be working on the fix ASAP but in the meantime, please use the tagged version 0.1-beta1 ([dockerhub](https://hub.docker.com/layers/144514027/hibiken/asynqmon/0.1-beta1/images/sha256-a13e6299a8f935ca8d1c8ca35f9a5a9b3a401b0a90e58fe6cce5c577de873304?context=explore), [release binary](https://github.com/hibiken/asynqmon/releases/tag/v0.1-beta1)).

**Comment by hibiken** [comment]
I fixed the issue and pushed the updated image to docker hub 👍 

Let me know if you are still seeing the issue!
